version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
    container_name: gb-data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: gb-admin