version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_gobarber
    container_name: gb-data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: gb-mongo

  redis:
    image: redis:6.0.9-alpine
    command: redis-server
    ports:
      - 6379:6379
    container_name: gb-cache

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: gb-admin
