name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      
      # instalar dependências do NPM/Yarn
      - name: Install Dependencies
        run: yarn
        
      # executar build do projeto
      - name: Run Build command
        run: yarn build
        
      # copiar arquivos gerados para o servidor
      - name: Copy Dist folder to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: ""
          
        # substituir o código existente pelo novo código
        # acessar servidor e instalar dependências
        # executar as migrações de banco de dados
        # restart do servidor Node.js
          
          
